name: picture_loading
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  dio: ^4.0.0
  flutter_dotenv: ^5.0.0
  freezed_annotation: ^0.14.0
  json_serializable: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  freezed: ^0.14.0
  build_runner:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env
    - assets/env/.env_development
